# Generated by Django 6.0.1 on 2026-01-18 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('primary_muscle', models.CharField(max_length=60)),
                ('secondary_muscle', models.CharField(blank=True, max_length=60)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
