# Generated by Django 6.0.1 on 2026-01-21 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0002_workout_workoutexercise_setentry'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exercise',
            options={},
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='primary_muscle',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='secondary_muscle',
        ),
        migrations.AddField(
            model_name='exercise',
            name='category',
            field=models.CharField(choices=[('legs', 'Legs'), ('back', 'Back'), ('chest', 'Chest'), ('shoulders', 'Shoulders'), ('biceps', 'Biceps'), ('triceps', 'Triceps'), ('core', 'Core'), ('cardio', 'Cardio'), ('full', 'Full Body')], default='full', max_length=20),
        ),
        migrations.AddField(
            model_name='exercise',
            name='default_equipment',
            field=models.CharField(choices=[('machine', 'Machine'), ('dumbbell', 'Dumbbell'), ('barbell', 'Barbell'), ('cable', 'Cable'), ('smith', 'Smith Machine'), ('bodyweight', 'Bodyweight'), ('cardio', 'Cardio Machine'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AddField(
            model_name='exercise',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
