# Generated by Django 6.0.1 on 2026-02-07 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workouts", "0003_alter_exercise_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="setentry",
            options={},
        ),
        migrations.AlterField(
            model_name="setentry",
            name="reps",
            field=models.PositiveSmallIntegerField(null=True, blank=True),
        ),
    ]
