# Generated by Django 6.0.1 on 2026-02-08 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0004_alter_setentry_options_setentry_duration_min_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='setentry',
            name='duration_min',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='setentry',
            name='incline',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='setentry',
            name='speed',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
