# Generated by Django 6.0.1 on 2026-01-17 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CheckIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('weight_lb', models.DecimalField(decimal_places=1, max_digits=5)),
                ('bodyfat_percent', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('muscle_lb', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('waist_in', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
    ]
